uwsgi:
    socket: /tmp/blog.sock
    master: 1
    daemonize: /var/www/blog/log/uwsgi.log
    wsgi-file: /var/www/blog/main_app.py
    pythonpath: /var/www/Projects/blog
    virtualenv: /root/.virtualenvs/blog
